In [5]:
import numpy as np
from numpy import *

In [11]:
list1 = [1, 2, 3]
arr1 = np.array (list1)
arr1

array([1, 2, 3])

In [28]:
np.zeros (5)

array([0., 0., 0., 0., 0.])

In [49]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
np.ones (7)

array([1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.empty (5)

array([0., 0., 0., 0., 0.])

In [32]:
np.arange (10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [34]:
np.random.rand(2, 3)

array([[0.69015787, 0.16819232, 0.71859485],
       [0.20574596, 0.29293131, 0.30452717]])

In [35]:
arr2 = np.arange (16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
arr2.reshape (4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
arr2.reshape (2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [40]:
arr2 = np.arange (16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
arr2.reshape (4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
arr2.reshape (2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [56]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
arr.shape

(16,)

In [58]:
arr.dtype

dtype('int32')

In [59]:
arr.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [60]:
arr [5]

5

In [61]:
arr [-1]

15

In [62]:
arr [5:8]

array([5, 6, 7])

In [63]:
arr2 = np.arange (16).reshape(4,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
arr2 [1]

array([4, 5, 6, 7])

In [65]:
arr2 [1][1]

5

In [66]:
arr2 [1,1]

5

In [68]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [69]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [70]:
score_arr [score_arr >= 90]

array([90, 95, 90])

In [77]:
arr = np.arange (1, 5)
arr

array([1, 2, 3, 4])

In [78]:
arr + 2

array([3, 4, 5, 6])

In [79]:
arr * 2

array([2, 4, 6, 8])

In [80]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [81]:
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [83]:
arr1 = np.arange (5, 9)
arr1

array([5, 6, 7, 8])

In [84]:
arr + arr1

array([ 6,  8, 10, 12])

In [85]:
list1 = [5, 6, 7, 8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [86]:
np.square(arr)

array([ 1,  4,  9, 16], dtype=int32)

In [91]:
np.exp (arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [92]:
np.log (arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [93]:
np.add (arr, arr1)

array([ 6,  8, 10, 12])

In [94]:
np.sum (arr)

10

In [95]:
np.cumsum (arr)

array([ 1,  3,  6, 10], dtype=int32)

In [96]:
np.mean (arr)

2.5

In [97]:
np.var (arr)

1.25

In [98]:
np.std (arr)

1.118033988749895

In [100]:
arr = np.arange (10).reshape (2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
arr.transpose ()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [103]:
arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [105]:
arr = np.arange (10).reshape (2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
np.save('array', arr)

In [107]:
load_arr = np.load('array.npy')
load_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])