In [70]:
import pandas as pd #pandas package import
from sklearn.preprocessing import LabelEncoder #범주형 데이터의 실수화 함수 import
from sklearn.preprocessing import OneHotEncoder #더미변수 생성, 가변환 함수 import

In [71]:
x_train = pd.DataFrame(["남성", "여성", "남성", "여성", "남성", "여성"], columns = ["성별"]) #데이터 set 생성
x_train.head(3) #데이터 확인

성별
0  남성
1  여성
2  남성

In [72]:
x_train.info() #데이터 프레임 정보 확인

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   성별      6 non-null      object
dtypes: object(1)
memory usage: 176.0+ bytes


In [75]:
x_train['성별'].value_counts() #범주형 데이터 갯수 확인

남성    3
여성    3
Name: 성별, dtype: int64

In [80]:
encoding = LabelEncoder() #레이블 인코더 생성

#x_train 데이터 이용하여 피팅하고 레이블 숫자로 변환
encoding.fit(x_train["성별"])
x_train["성별_인코딩"] = encoding.transform(x_train["성별"])

In [78]:
x_train

성별  성별_인코딩
0  남성       0
1  여성       1
2  남성       0
3  여성       1
4  남성       0
5  여성       1

In [81]:
print(list(encoding.classes_)) #클래스 확인
print(list(encoding.inverse_transform([1,0]))) #인코딩 값으로 문자값 확인

['남성', '여성']
['여성', '남성']


In [20]:
x_train.head(2)

성별  성별_인코딩
0  남성       0
1  여성       1

In [82]:
one_encoding = OneHotEncoder (sparse = False) #원핫인코더 생성
one_encoding.fit (x_train [["성별"]]) #x_train 데이터 이용하여 피팅

#가변환값 변환
one_encoding.transform (x_train[["성별"]]) 
one_encoding.fit_transform(x_train[["성별"]])

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [84]:
print(one_encoding.get_feature_names()) #가변환된 피쳐 확인

['x0_남성' 'x0_여성']


In [86]:
#가변환된 값을 x_train_one 데이터 프레임으로 저장
x_train_one = pd.DataFrame (one_encoding.transform (x_train[['성별']]), columns = ['성별0', '성별1'])

In [87]:
#x_train 데이터와 x_train_one의 가변환된 속성 합침
x_train = pd.concat ([x_train, x_train_one], axis = 1)

In [88]:
x_train.head(3) #결과 확인

성별  성별_인코딩  성별0  성별1
0  남성       0  1.0  0.0
1  여성       1  0.0  1.0
2  남성       0  1.0  0.0

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
corpus = ['청년 인재 개발 양성 과정',
          '인공지능 청년 양성',
          '미래 인공지능 데이터 대한민국',
          '데이터 원유 기술사 청년 개발',]

In [32]:
corpus

['청년 인재 개발 양성 과정', '인공지능 청년 양성', '미래 인공지능 데이터 대한민국', '데이터 원유 기술사 청년 개발']

In [33]:
type(corpus)

list

In [34]:
count_vect = CountVectorizer() #카운트 벡터라이저 생성

In [35]:
count_vect.fit(corpus) #단어 카운트

CountVectorizer()

In [36]:
count_vect.vocabulary_ #단어 확인

{'청년': 10,
 '인재': 9,
 '개발': 0,
 '양성': 6,
 '과정': 1,
 '인공지능': 8,
 '미래': 5,
 '데이터': 4,
 '대한민국': 3,
 '원유': 7,
 '기술사': 2}

In [37]:
count_vect.transform(corpus).toarray() #단어 벡터화한 값을 array로 변환하여 확인

array([[1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1]], dtype=int64)

In [89]:
features = count_vect.transform(corpus) #단어 벡터화

In [39]:
features

<4x11 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [45]:
vocab = count_vect.get_feature_names() #속성 이름만 변환

In [46]:
vocab

['개발', '과정', '기술사', '대한민국', '데이터', '미래', '양성', '원유', '인공지능', '인재', '청년']

In [91]:
DTM = pd.DataFrame(features.toarray(), columns = vocab).head() #문서단어행렬을 데이터 프레임으로 변환

In [48]:
DTM

개발  과정  기술사  대한민국  데이터  미래  양성  원유  인공지능  인재  청년
0   1   1    0     0    0   0   1   0     0   1   1
1   0   0    0     0    0   0   1   0     1   0   1
2   0   0    0     1    1   1   0   0     1   0   0
3   1   0    1     0    1   0   0   1     0   0   1

In [92]:
count_vect.transform(['기술사 대한민국 인재 만세']).toarray() #문서단어행렬에 일치하는 단어 확인

array([[0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0]], dtype=int64)

In [51]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [52]:
corpus

['청년 인재 개발 양성 과정', '인공지능 청년 양성', '미래 인공지능 데이터 대한민국', '데이터 원유 기술사 청년 개발']

In [93]:
tfid = TfidfVectorizer() #TF-IDF 벡터라이저 생성
tfid.fit(corpus) #단어 카운트
tfid.vocabulary_ #단어사전 확인

{'청년': 10,
 '인재': 9,
 '개발': 0,
 '양성': 6,
 '과정': 1,
 '인공지능': 8,
 '미래': 5,
 '데이터': 4,
 '대한민국': 3,
 '원유': 7,
 '기술사': 2}

In [94]:
tfid.transform(corpus).toarray() #단어 벡터화한 값을 array로 변환하여 확인

array([[0.41263976, 0.52338122, 0.        , 0.        , 0.        ,
        0.        , 0.41263976, 0.        , 0.        , 0.52338122,
        0.33406745],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.61366674, 0.        , 0.61366674, 0.        ,
        0.49681612],
       [0.        , 0.        , 0.        , 0.55528266, 0.43779123,
        0.55528266, 0.        , 0.        , 0.43779123, 0.        ,
        0.        ],
       [0.41263976, 0.        , 0.52338122, 0.        , 0.41263976,
        0.        , 0.        , 0.52338122, 0.        , 0.        ,
        0.33406745]])

In [95]:
features_idf = tfid.transform (corpus) #단어 벡터화
features_idf

<4x11 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [97]:
vocab_idf = count_vect.get_feature_names() #속성 이름만 변환

In [65]:
vocab_idf

['개발', '과정', '기술사', '대한민국', '데이터', '미래', '양성', '원유', '인공지능', '인재', '청년']

In [98]:
DTM_idf = pd.DataFrame(features_idf.toarray (), columns = vocab_idf).head() #문서단어행렬을 데이터 프레임으로 변환

In [69]:
DTM_idf

개발        과정       기술사      대한민국       데이터        미래        양성  \
0  0.41264  0.523381  0.000000  0.000000  0.000000  0.000000  0.412640   
1  0.00000  0.000000  0.000000  0.000000  0.000000  0.000000  0.613667   
2  0.00000  0.000000  0.000000  0.555283  0.437791  0.555283  0.000000   
3  0.41264  0.000000  0.523381  0.000000  0.412640  0.000000  0.000000   

         원유      인공지능        인재        청년  
0  0.000000  0.000000  0.523381  0.334067  
1  0.000000  0.613667  0.000000  0.496816  
2  0.000000  0.437791  0.000000  0.000000  
3  0.523381  0.000000  0.000000  0.334067